### PR TITLE
:lock: fix: mocha in audit

### PR DESCRIPTION
**Pull request by aashutoshrathi**

### CODE REVIEW

**Review by sadakyle — APPROVED** [review]

**Comment by sadakyle** [comment]
I really appreciate you looking at this so quickly 🙏

**Comment by aashutoshrathi** [comment]
v1.2.6 is live already

**Comment by wellwelwel** [comment]
@aashutoshrathi, what do you think about enabling the tests to CI Workflows?
It would ensure safety in further changes.

For example, you can use the matrixes of the most current **NodeJS** version (20) and of the last two LTS (18 and 16).

It doesn't requires a patch release, but could even help in community contributions.

---

You can also activate the `Issue` section 🙋🏻‍♂️

**Comment by aashutoshrathi** [comment]
Hey! @wellwelwel sure.
Let me enable all tabs for this repo

**Pull request merged**
