### PR TITLE
:arrow_up: v1.2.7

### PR DESCRIPTION
**Pull request by aashutoshrathi**

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@wellwelwel @emilorol if you folks think, it's good to go, we can ship it

**Comment by wellwelwel** [comment]
@aashutoshrathi, I have some small suggestions:

1. On LICENSE, instead `2014-2023`, to `2014-current`
2. The `.npmignore` is serving no purpose, since in `package.json`, it only requires the files `index.js` and `index.d.ts` to package.

Forward, we can remove completely the `verb` and the `gulp-format-md`.
But I think that any new change should be with CI already enabled 🙋🏻‍♂️

**Comment by aashutoshrathi** [comment]
> @aashutoshrathi, I have some small suggestions:
> 
> 1. On LICENSE, instead `2014-2023`, to `2014-current`
> 2. The `.npmignore` is serving no purpose, since in `package.json`, it only requires the files `index.js` and `index.d.ts` to package.
> 
> Forward, we can remove completely the `verb` and the `gulp-format-md`. But I think that any new change should be with CI already enabled 🙋🏻‍♂️

Should we do this in this version?

**Comment by wellwelwel** [comment]
Since after this **PR** the tests will be enabled, I think this should come next.

**Review by wellwelwel — APPROVED** [review]

**Comment by aashutoshrathi** [comment]
> Since after this **PR** the tests will be enabled, I think this should come next. What do you think?

Makes sense to me.
But one thing worries me, since this is like a really important repo for all the folks, and we are more or less making non-functional releases, should we even makes releases or just update the docs, without releasing it?

**Comment by wellwelwel** [comment]
@aashutoshrathi, I will give my point about that.

For CI and general tasks (chore), I never release a new version.
For documentation, it depends.

In this **PR**, the changes in documentation are relevant:
- It fix the installation to correct package
- It shows a workaround for deep dependencies

About your changes for **bower**, in case you use it, it's okay.
If you don't use the **bower**, this could be quietly removed. Some files only makes sense for the development of the original creator. The same for `verb` and `gulp-format-md`.

But, since (for some reason), the `gulp-format-md` is a direct dependency, even though it's not used in the project. Then, it will requires a new patch. If it weren't for that, or the `gulp-format-md` was just a development dependency, a new release wouldn't be necessary.

**Comment by wellwelwel** [comment]
One possibility would be to merge this PR without releasing it.
So, it would turn on the CI and when every small change is ready, release it.

**Comment by aashutoshrathi** [comment]
I think let's not bump the version and merge this PR

**Comment by aashutoshrathi** [comment]
Also, I don't think it requires, publishing, right?

**Comment by wellwelwel** [comment]
Since your concern is to release without significant changes, I suggest waiting until you have enough changes together that you feel safe to release it 🙋🏻‍♂️

> Just a note, although the installation appears right on GitHub after the merge, in NPM it will still lead to the original project.

**Pull request merged**
